### ISSUE TITLE
Split data sheets per year

### ISSUE THREAD

**Issue by AmnezziaCS** [AmnezziaCS/HenriBot#27]
# Why ?
Since the scholar year is over soon. It would be good to create a new tab/sheet for next year.

## What is it exactly in the sheet ?
<img width="302" alt="image" src="https://github.com/amnezziaa/HenriBot/assets/94064103/5b9bb287-eed4-4f31-afe6-b3f2279c4028">

## Difficulties :
Making such changes would require the code to be re-adjusted since at the moment we are not targeting a specific `data window` (referring to the picture) and we are also using a set `starting date` in `.env`. https://github.com/amnezziaa/HenriBot/blob/bca9d1780dd094d86b907f2018480f3f38934d14/example.env#L12

## How ?
- I think a good idea is to only specify the `year` in the `.env` file and to setup the bot in a way he knows what the `starting date` for that year is.
- I also need to check back on the `2022-2023` data to make sure all of it makes sense.

## Note :
I will look into this issue and see what's possible **soon** (hopefully). @Sterbenfr if you have any ideas don't hesitate to write down something underneath 👍

**Comment by amnezziaa** [comment]
I just thought that we should create a `command` that grabs the `data` from the `previous year` so we can see it while the other year is going.
